In [1]:
#importing numpy library
import numpy as np

#Vandermonde matrix calculation function
def AlexandreTheophileVandermonde(lst,N): 
    x = np.array(lst)
    output_matrix = np.vander(x, N)
    print(output_matrix)

#1-D input array.
input_lst = [1,2,3,5]

#Number of columns in the output
N = int(input("Enter the number of columns in the matrix"))

#calling the function
AlexandreTheophileVandermonde(input_lst,N)




Enter the number of columns in the matrix3
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
